---
title: "Cibersort Prostate Cancer scRNA"
output: html_notebook
---

```{r}
#Load libraries for Seurat pipeline
library(SingleCellExperiment)
library(Seurat)
library(tidyverse)
library(viridis)
library(Matrix)
```


```{r}
#Define methods for Seurat object class to make reference df from scRNA data


#Function to obtain random sample of cell ids for specified samples and celltypes - default rs of 5 cells 
GetCellID <- function(object, celltype, samples, number) {
  id <- object@meta.data %>% filter(sample %in% samples & cluster %in% celltype) %>% .$cells
  sample(x = id, size = number, replace = T)
}

#Function to generate CPM expression for cell ids from log2 TP10K+1 data
GetCPM <- function(object, celltype, samples, ...) {
   cellids <- GetCellID(object = object, celltype = celltype, samples = samples, ...)
   counts <- GetAssayData(object = object, slot = "counts")[, WhichCells(object = object, cells = cellids)] %>% Matrix(sparse = T)
   rownames(counts) <- GetAssayData(object = object, slot = "counts") %>% rownames()
   counts@x <- (2^(counts@x) - 1)*100 
   counts %>% as.data.frame()
}

#Create reference df for cells of each cell type using specified samples - must supply seurat object with column "cluster" of cell idents in metadata slot
MakeReference <- function(object, samples, celltypes, ...){
   output <- NULL

   for (cell in celltypes) {
      tempdf <- GetCPM(object = object, celltype = cell, samples = samples, ...)
      tempdf <- data.frame(rownames(tempdf), tempdf)
      colnames(tempdf) <- c("Genes", paste0(cell, c(1:(ncol(tempdf) - 1))))
      print(paste0("Processing celltype: ", cell))
      ifelse(is.null(output), output <- tempdf, output <- inner_join(output, tempdf, by = "Genes"))
      }
   output
}
```


```{r}
#Subroutines to make mixture matrix and cell fractions

#Obtain cf for a celltype, sample combination
GetCellFraction <- function(object, celltype, specific_sample){
  cf_df <- object@meta.data %>% filter(sample == specific_sample) %>% select(cluster) %>% table() %>% as.data.frame() %>% mutate(Fraction = Freq/sum(Freq))
  colnames(cf_df) <- c("Cell", "Freq", "Fraction")
  cf_df %>% filter(Cell == celltype) %>% .$Fraction
}

#Create GEP df using Seurat object, a df indicating celltype, sample and fraction combination, and the total number of cells in mixture
GetGEP <- function(object, cell_dataframe, number_of_cells){
  gep <- NULL
  
  #Get GEP for respective celltype, sample and fraction for mixture according to df - column of genes and columns for celltype gep
    for (k in 1:nrow(cell_dataframe)){
      if ((cell_dataframe[k,3] * number_of_cells) >= 1){
        tempdf <- GetCPM(object = object, celltype = cell_dataframe[k,1], samples = cell_dataframe[k,2], number = (number_of_cells * cell_dataframe[k,3]))
        tempdf <- data.frame(rownames(tempdf), tempdf)
        colnames(tempdf) <- c("Genes", paste0(cell_dataframe[k,1], c(1:(ncol(tempdf) - 1))))
        ifelse(is.null(gep), gep <- tempdf, gep <- inner_join(gep, tempdf, by = "Genes"))
      }
    }
  gep
}

#Make single tumor mixture using either stratified or simple random sampling
MakeSingleMix <- function(object, number_of_cells, samples, celltypes, method){
  
  #Pick random permutation of celltype and sample
  s <- sample(samples, length(celltypes), replace = T)
  df <- data.frame(Cell = celltypes, Sample = s)
  
  #Create [cell, sample, fraction] df using either stratified or simple random sampling procedure
  if (method == "stratified"){
    cf <- NULL
    #Get cell fractions for combination of celltype and sample - store in df - renormalize so sum to 1
    for (j in 1:nrow(df)){
    cf <- GetCellFraction(object = object, celltype = df[j,1], specific_sample = df[j,2]) %>% append(cf)}
    df$Fraction <- rev(cf)/sum(cf)
  
} else if (method == "simple") {
    df$Fraction <- rnorm(n = length(celltypes), mean = 1/(length(celltypes)), sd =  1/(2* length(celltypes))) %>% abs()
    df$Fraction <- df$Fraction/sum(df$Fraction)
}
  #Call method to make GEP using df
  gep <- GetGEP(object = object, cell_dataframe = df, number_of_cells = number_of_cells)
  
  #Sum and CPM normalize cells in mixture - append to cell_mix df
  mix <- gep[,-1] %>% rowSums()
  list(data.frame(gep[,1], (mix/sum(mix))*1000000), df)
}


MakeManyMix <- function(object, number_of_cells, samples, celltypes, number_of_mixtures, method){
  many_mix <- NULL
  many_frac <- NULL
  
  #Loop thru number of mixtures - 
  for (i in 1:number_of_mixtures){
    
    #Set seed
    set.seed(i)
    
    #Create tumor mixture
    single_mix <- MakeSingleMix(object = object, number_of_cells = number_of_cells, samples = samples, celltypes = celltypes, method = method)
    
    #Formatting
    colnames(single_mix[[1]]) <- c("Genes", paste0("M", i))
    print(paste0("Processing mixture: ", i))
    ifelse(is.null(many_mix), many_mix <- single_mix[[1]], many_mix <- inner_join(many_mix, single_mix[[1]], by = "Genes"))

    cf <- single_mix[[2]][,c(1,3)]
    colnames(cf) <- c("Cell", paste0("M", i))
    ifelse(is.null(many_frac), many_frac <- cf, many_frac <- inner_join(many_frac, cf, by = "Cell"))
  }
  list(many_mix, many_frac)
}
```



```{r}
#Load data and make signature/mix Seurat objects and count data
scrna <- readRDS("/Users/ds/Desktop/scratch/R/PCa_scRNA_Named_All_Cluster.RDS")

#Build signature matrix on 4 samples
sig_samples <- c("Sample1", "Sample3", "Sample5", "Sample7")
mix_samples <- c("Sample2", "Sample4", "Sample6", "Sample8")

#Add column labeled "cluster" for cell cluster identities to metadata - metadata should also have column labeled "sample" to denote sample label
scrna@meta.data <- data.frame(cells = names(Idents(scrna)), cluster = Idents(scrna)) %>% merge(scrna@meta.data)

cell_levels <- scrna$cluster %>% levels()
cell_levels <- cell_levels[which(!cell_levels %in% c("18", "14"))]
```

```{r}
filepath <- "/Users/ds/Desktop/scratch/R/"

#Create reference for making the signature matrix with Cibersort
ref <- MakeReference(object = scrna, samples = sig_samples, celltypes = cell_levels, number = 50)

#Format
types <- gsub(x = colnames(ref)[-1], pattern = "[0-9]*$", replacement = "") %>% unique()
colnames(ref) <- c("Genes", rep(types, each = 50))
write.table(ref, file =  paste0(filepath, "reference.txt"), quote = F, row.names = F, sep = "\t" )

#Create mixtures
mixture <- MakeManyMix(object = scrna, number_of_cells = 1000, samples = mix_samples, celltypes = cell_levels, number_of_mixtures = 20, method = "simple")

#Format
write.table(mixture[[1]], file = paste0(filepath, "simp_mixture.txt"), quote = F, row.names = F, sep = "\t")
```



```{r}
#Plotting

#Read in results - dimension: mixtures by celltypes
cibersort <- read.table(file = "/Users/ds/Desktop/scratch/R/CIBERSORTx_Job28_Results.txt", header = T, sep = "\t")
cf <- mixture[[2]]

#Formatting
cibersort <- cibersort %>% select(-c("P.value", "Correlation", "RMSE"))

cells <- cf$Cell 
cf <- cf[,-1] %>% t() %>% as.data.frame()
colnames(cf) <- cells
cf$Mixture = rownames(cf)

#Plot stacked barplot for celltype in each mixture
gather(cibersort, key = Cell_type, value = Fraction, -Mixture) %>% ggplot(aes(x = Mixture, y = Fraction, fill = Cell_type )) + geom_col(position = "stack") + ggtitle("Cibersort cell fraction") + scale_fill_viridis_d() 

gather(cf, key = Cell_type, value = Fraction, -Mixture) %>% ggplot(aes(x = Mixture, y = Fraction, fill = Cell_type )) + geom_col(position = "stack") + scale_fill_viridis_d() + ggtitle("Ground truth cell fraction") + ylim(0,1)

#Formatting
cibersort <- cibersort %>% select(-c("Mixture"))
cf <- cf %>% select(-c("Mixture"))

#Plot correlation barplots
data.frame(Mixture = paste0("M", 1:20), Correlation = sapply(1:20, FUN = function(y){cor(as.numeric(cibersort[y,]), as.numeric(cf[y,]))})) %>% ggplot(aes(x = Mixture, y = Correlation)) + geom_col(fill = viridis(1)) + ggtitle("Correlation across mixtures") 

data.frame(Celltype = cell_levels, Correlation = sapply(1:7, FUN = function(y){cor(as.numeric(cibersort[,y]), as.numeric(cf[,y]))})) %>% ggplot(aes(x = Celltype, y = Correlation)) + geom_col(fill = viridis(1)) + ggtitle("Correlation across cells") 


```


